import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import ts from'typescript';import*as jsx from'react/jsx-runtime';
let slots=[],cursor=0,effects=[],requests=[];
const cfg={provider:'ollama',model:'qwen3:8b',agent_url:'http://localhost:11434',project_directory:'',image_url:'http://localhost:19877',image_token:'',steps:30,cfg:4,audio_url:'http://localhost:19876',audio_token:'',tts_model:'qwen3-tts',tts_language:'Chinese',tts_speaker:'vivian'};
const mod={};const source=ts.transpileModule(readFileSync(new URL('../src/SettingsPanel.tsx',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;
new Function('require','exports',source)(name=>{if(name==='react/jsx-runtime')return jsx;if(name==='react')return{useState:v=>{const i=cursor++;if(!(i in slots))slots[i]=v;return[slots[i],n=>slots[i]=typeof n==='function'?n(slots[i]):n];},useEffect:fn=>effects.push(fn)};if(name==='./api')return{api:async(path,options)=>{if(options)requests.push(JSON.parse(options.body));return cfg;}};return new Proxy({},{get:()=>()=>null});},mod);
let tree;function render(){cursor=0;tree=mod.default({report:e=>{throw e;}});}function nodes(v){if(!v||typeof v!=='object')return[];if(Array.isArray(v))return v.flatMap(nodes);return[v,...nodes(v.props?.children)];}function all(){return nodes(tree);}function clickTab(id){all().find(n=>n.props?.id==='settings-tab-'+id).props.onClick();render();}function panel(id){return all().find(n=>n.props?.id==='settings-panel-'+id);} 
render();effects[0]();await Promise.resolve();render();assert.equal(all().filter(n=>n.props?.role==='tab').length,5);assert.equal(panel('appearance').props.hidden,false);
clickTab('agent');nodes(panel('agent')).find(n=>n.type==='input'&&n.props.list==='agent-models').props.onChange({target:{value:'custom-model'}});render();clickTab('audio');clickTab('agent');assert.equal(nodes(panel('agent')).find(n=>n.type==='input'&&n.props.list==='agent-models').props.value,'custom-model');
for(const id of ['storage','image','audio']){clickTab(id);assert.equal(panel(id).props.hidden,false);assert.equal(all().filter(n=>n.props?.role==='tabpanel'&&!n.props.hidden).length,1);}
await all().find(n=>n.type==='button'&&n.props.children==='保存配置').props.onClick();assert.equal(requests[0].model,'custom-model');clickTab('appearance');assert(!all().some(n=>n.type==='button'&&n.props.children==='保存配置'));
console.log('Settings tabs: categories, visibility, unsaved edits retained and combined save passed');
