import {initializeUIPreferences,getUIPreferences} from '@local-ai/ui';
import {getCurrentWindow} from '@tauri-apps/api/window';
import {AutocompleteSelect} from '@local-ai/ui';
import {confirmAction} from '../../../packages/ui/src/confirm';
import {Dialog,InfoTip} from '../../../packages/ui/src/Dialog';
import {initializeTheme} from '../../../packages/ui/src/index';
import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke,isTauri} from '@tauri-apps/api/core';
import {ArrowDown,ArrowUp,Brush,Check,ChevronDown,Copy,Download,Eye,EyeOff,FilePlus,FolderOpen,ImagePlus,Layers,Loader2,Lock,MousePointer2,RotateCcw,Save,Settings,SlidersHorizontal,Sparkles,SquareDashed,Trash2,Unlock,Upload,X} from 'lucide-react';
import {Button,Toast} from '../../../packages/ui/src/index';
import '../../../packages/ui/src/styles.css';
import {api,connect,download,request,upload} from './api';
import {type Layer,type Project,type Mode,modes,emptyProject,parseProject,dataURL,loadImage,renderLayers,canvasBlob} from './project';
import './style.css';
import {ImageSettings} from './ImageSettings';
import {RecentOperations} from './RecentOperations';

type Job={id:string;created:number;status:string;progress:number;file:string|null;error:string|null;request:{mode:Mode;prompt:string;seed:number}};
type Tool='move'|'brush'|'circle';
function App(){
 const [p,setP]=useState<Project>(emptyProject),[tool,setTool]=useState<Tool>('move'),[brush,setBrush]=useState(40),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[message,setMessage]=useState(''),[settings,setSettings]=useState(false),[config,setConfig]=useState<any>(null),[token,setToken]=useState(''),[zoom,setZoom]=useState(60),[history,setHistory]=useState<Project[]>([]),[redo,setRedo]=useState<Project[]>([]);
 const stage=useRef<HTMLCanvasElement>(null),maskCanvas=useRef<HTMLCanvasElement>(null),file=useRef<HTMLInputElement>(null),projectFile=useRef<HTMLInputElement>(null),maskFile=useRef<HTMLInputElement>(null),drag=useRef<{x:number;y:number;layer?:Layer;before:Project;mask?:ImageData}|null>(null),latest=useRef(p);latest.current=p;
 const [previews,setPreviews]=useState<Record<string,string>>({});const urls=useRef<Record<string,string>>({});
 const notify=(e:unknown)=>setMessage(e instanceof Error?e.message:String(e));
 const change=(next:Project)=>{setHistory(h=>[...h.slice(-19),latest.current]);setRedo([]);setP(next);};
 const patch=(values:Partial<Project>)=>change({...p,...values});
 const layer=p.layers.find(l=>l.id===p.active);
 const editLayer=(values:Partial<Layer>)=>patch({layers:p.layers.map(l=>l.id===p.active?{...l,...values}:l)});
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(t);}},[message]);
 useEffect(()=>{let gone=false;let polling=false;const tick=async()=>{if(polling)return;polling=true;try{await connect();const list=await api<Job[]>('/v1/jobs');if(!gone){setJobs(list);setConnected(true);}}catch{if(!gone)setConnected(false);}finally{polling=false;}};void tick();const id=setInterval(tick,2500);return()=>{gone=true;clearInterval(id);};},[]);
 useEffect(()=>{let disposed=false;void(async()=>{for(const job of jobs){if(job.status==='completed'&&!urls.current[job.id]){try{const blob=await(await request(`/v1/jobs/${job.id}/image`)).blob();if(disposed)return;urls.current[job.id]=URL.createObjectURL(blob);setPreviews({...urls.current});}catch(e){notify(e);}}}})();return()=>{disposed=true;};},[jobs]);
 useEffect(()=>()=>Object.values(urls.current).forEach(URL.revokeObjectURL),[]);
 useEffect(()=>{let gone=false;void renderLayers(p,p.layers).then(c=>{if(!gone&&stage.current){const ctx=stage.current.getContext('2d')!;ctx.clearRect(0,0,p.width,p.height);ctx.drawImage(c,0,0);}}).catch(notify);return()=>{gone=true;};},[p]);
 useEffect(()=>{let gone=false;const ctx=maskCanvas.current?.getContext('2d');ctx?.clearRect(0,0,p.width,p.height);if(p.mask)void loadImage(p.mask).then(img=>{if(!gone)ctx?.drawImage(img,0,0,p.width,p.height);}).catch(notify);return()=>{gone=true;};},[p.mask,p.width,p.height]);
 async function addFiles(files:FileList|File[]){try{const layers:Layer[]=[];for(const f of Array.from(files)){if(f.size>32*1024*1024)throw Error('单张图片不能超过 32 MB');if(!['image/png','image/jpeg','image/webp'].includes(f.type))throw Error('支持 PNG、JPEG、WebP');const source=await dataURL(f),im=await loadImage(source);if(im.width*im.height>20_000_000)throw Error('图片不能超过 2000 万像素');layers.push({id:crypto.randomUUID(),name:f.name,source,width:im.width,height:im.height,x:0,y:0,scale:Math.min(p.width/im.width,p.height/im.height,1),opacity:1,visible:true,locked:false,reference:true});}if(p.layers.length+layers.length>50)throw Error('最多 50 个图层');patch({layers:[...p.layers,...layers],active:layers.at(-1)?.id??p.active});}catch(e){notify(e);}}
 function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*p.width/r.width,y:(e.clientY-r.top)*p.height/r.height};}
 function pointerDown(e:React.PointerEvent<HTMLCanvasElement>){if(tool==='move'&&(!layer||layer.locked))return;const pos=point(e),ctx=e.currentTarget.getContext('2d')!;drag.current={...pos,layer,before:p,mask:ctx.getImageData(0,0,p.width,p.height)};e.currentTarget.setPointerCapture(e.pointerId);if(tool==='brush'){ctx.beginPath();ctx.fillStyle='white';ctx.arc(pos.x,pos.y,brush/2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(pos.x,pos.y);}}
 function pointerMove(e:React.PointerEvent<HTMLCanvasElement>){const d=drag.current;if(!d)return;const pos=point(e),ctx=e.currentTarget.getContext('2d')!;if(tool==='move'&&d.layer)setP({...d.before,layers:d.before.layers.map(l=>l.id===d.layer!.id?{...l,x:Math.round(d.layer!.x+pos.x-d.x),y:Math.round(d.layer!.y+pos.y-d.y)}:l)});else if(tool==='brush'){ctx.strokeStyle='white';ctx.lineWidth=brush;ctx.lineCap='round';ctx.lineTo(pos.x,pos.y);ctx.stroke();}else if(tool==='circle'){ctx.putImageData(d.mask!,0,0);ctx.fillStyle='white';ctx.beginPath();ctx.ellipse((pos.x+d.x)/2,(pos.y+d.y)/2,Math.abs(pos.x-d.x)/2,Math.abs(pos.y-d.y)/2,0,0,Math.PI*2);ctx.fill();}}
 function pointerUp(e:React.PointerEvent<HTMLCanvasElement>){const d=drag.current;if(!d)return;drag.current=null;setHistory(h=>[...h.slice(-19),d.before]);setRedo([]);if(tool!=='move'){const mask=e.currentTarget.toDataURL('image/png');setP(v=>({...v,mask,mode:tool}));}}
 async function exportProject(){await download(new Blob([JSON.stringify(p)],{type:'application/json'}),`${p.name||'project'}.laimage`);notify('工程已导出，包含原始图层与遮罩');}
 async function importProject(f:File){try{if(f.size>200*1024*1024)throw Error('工程不能超过 200 MB');const next=parseProject(JSON.parse(await f.text()));await Promise.all(next.layers.map(l=>loadImage(l.source)));if(next.mask)await loadImage(next.mask);change(next);notify('工程已导入');}catch(e){notify(e);}}
 async function generate(){setBusy(true);try{const active=p.layers.filter(l=>l.visible&&l.reference);if(active.length>10)throw Error('最多选择 10 个参考图层');const references:string[]=[];for(const l of active){const image=await renderLayers(p,[l]);references.push((await upload(await canvasBlob(image))).id);}let mask:string|undefined;if(['brush','circle','mask'].includes(p.mode)){if(!p.mask)throw Error('请绘制或上传遮罩');const c=document.createElement('canvas');c.width=p.width;c.height=p.height;const ctx=c.getContext('2d')!;ctx.fillStyle='black';ctx.fillRect(0,0,p.width,p.height);ctx.drawImage(await loadImage(p.mask),0,0);mask=(await upload(await canvasBlob(c),'mask.png')).id;}const job=await api<Job>('/v1/jobs',{method:'POST',body:JSON.stringify({mode:p.mode,prompt:p.prompt,negative:p.negative,references,mask,width:p.width,height:p.height,steps:p.steps,cfg:p.cfg,seed:p.seed})});setJobs(v=>[job,...v]);notify('任务已加入队列');}catch(e){notify(e);}finally{setBusy(false);}}
 async function useResult(job:Job){try{const blob=await(await request(`/v1/jobs/${job.id}/image`)).blob();await addFiles([new File([blob],`${job.id.slice(0,8)}.png`,{type:'image/png'})]);setP(v=>({...v,mode:'continue'}));}catch(e){notify(e);}}
 const reorder=(delta:number)=>{const layers=[...p.layers],i=layers.findIndex(l=>l.id===p.active),j=i+delta;if(j>=0&&j<layers.length){[layers[i],layers[j]]=[layers[j],layers[i]];patch({layers});}};
 const undo=()=>{if(history.length){setRedo(v=>[...v,p]);setP(history.at(-1)!);setHistory(v=>v.slice(0,-1));}};
 const redoAction=()=>{if(redo.length){setHistory(v=>[...v,p]);setP(redo.at(-1)!);setRedo(v=>v.slice(0,-1));}};
 return <div className="editor">
  <header><div className="brand"><img className="app-logo" src="/image-logo.svg" alt=""/> LOCAL AI <span>IMAGE</span></div><input className="project-name" aria-label="工程名称" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/><span className={'connection '+(connected?'ready':'')}>{connected?'已连接':'服务未连接'}</span><Button title="新建工程" onClick={async()=>{if(p.layers.length||p.prompt){if(!await confirmAction('新建工程前请先导出，未导出的修改将丢失。继续？'))return;}change(emptyProject());}}><FilePlus size={16}/></Button><RecentOperations project={p} connected={connected} restore={next=>{change(next);setTool(next.mode==='brush'||next.mode==='circle'?next.mode:'move');}} notify={notify}/><Button onClick={()=>projectFile.current?.click()}><FolderOpen size={16}/>导入工程</Button><Button onClick={()=>void exportProject().catch(notify)}><Save size={16}/>导出工程</Button><Button title="模型与服务配置" onClick={()=>{setSettings(true);void api('/v1/config').then(setConfig).catch(notify);}}><Settings size={17}/></Button></header>
  <div className="workspace">
   <aside className="tools">{([["move",MousePointer2,"移动图层"],["brush",Brush,"涂抹遮罩"],["circle",SquareDashed,"圈选区域"]] as const).map(([key,Icon,title])=><button key={key} className={tool===key?'selected':''} title={title} onClick={()=>setTool(key)}><Icon size={20}/></button>)}<hr/><button title="添加图片图层" onClick={()=>file.current?.click()}><ImagePlus size={20}/></button><button title="导入独立遮罩" onClick={()=>maskFile.current?.click()}><Upload size={19}/></button><hr/><button title="撤销" disabled={!history.length} onClick={undo}><RotateCcw size={19}/></button><button title="重做" disabled={!redo.length} onClick={redoAction}><RotateCcw size={19} style={{transform:'scaleX(-1)'}}/></button></aside>
   <main><div className="canvas-bar"><span>{p.width} × {p.height} · RGBA</span>{tool!=='move'&&<><label>画笔 <input type="range" min="4" max="160" value={brush} onChange={e=>setBrush(+e.target.value)}/></label><button onClick={()=>patch({mask:null})}>清除遮罩</button></>}<label className="zoom">缩放 <AutocompleteSelect value={zoom} onChange={e=>setZoom(+e.target.value)}>{[25,40,50,60,75,100,150].map(v=><option key={v} value={v}>{v}%</option>)}</AutocompleteSelect></label></div>
    <div className="canvas-scroll" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void addFiles(e.dataTransfer.files);}}><div className="canvas-wrap checker" style={{width:p.width*zoom/100,height:p.height*zoom/100}}><canvas ref={stage} width={p.width} height={p.height}/><canvas className={'mask '+(tool==='move'?'moving':'drawing')} ref={maskCanvas} width={p.width} height={p.height} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={e=>{drag.current=null;setP(v=>({...v}));}}/>{!p.layers.length&&<div className="empty-canvas"><ImagePlus size={35}/><b>从一句描述或一张图片开始</b><span>拖入图片作为图层，或在右侧输入提示词</span><Button onClick={()=>file.current?.click()}>添加图片</Button></div>}</div></div>
    <section className="results"><div className="section-title"><b>生成记录</b><span>{jobs.length}</span></div><div className="result-strip">{!jobs.length&&<p className="muted">生成结果会保留在这里，可作为新图层继续编辑。</p>}{jobs.map(j=><article className="result" key={j.id}>{previews[j.id]?<img className="checker" src={previews[j.id]} alt={j.request.prompt}/>:<div className="job-state">{['queued','running'].includes(j.status)?<Loader2 className="spin"/>:<span>!</span>}<small>{({queued:'排队中',running:'生成中',failed:'失败',cancelled:'已取消'} as Record<string,string>)[j.status]} {j.status==='running'?`${j.progress}%`:''}</small></div>}<div><b>{modes[j.request.mode]}</b><small title={j.request.prompt}>{j.request.prompt}</small>{j.error&&<details><summary>查看错误</summary><p>{j.error}</p></details>}<div className="result-actions">{j.status==='completed'?<><button onClick={()=>void useResult(j)}><ImagePlus size={14}/>作为图层</button><button title="下载 PNG" onClick={()=>void request(`/v1/jobs/${j.id}/image`).then(r=>r.blob()).then(b=>download(b,`${j.id}.png`)).catch(notify)}><Download size={14}/></button></>:['queued','running'].includes(j.status)&&<button onClick={()=>void api(`/v1/jobs/${j.id}/cancel`,{method:'POST'}).catch(notify)}>取消</button>}</div></div></article>)}</div></section>
   </main>
   <aside className="properties"><section><div className="section-title"><b><SlidersHorizontal size={16}/> 画布</b><AutocompleteSelect value={`${p.width}x${p.height}`} onChange={e=>{const [width,height]=e.target.value.split('x').map(Number);patch({width,height,mask:null});}}>{[[1024,1024],[1344,768],[768,1344],[2048,1024],[1024,2048],[512,512]].map(([w,h])=><option key={w+'x'+h} value={w+'x'+h}>{w} × {h}</option>)}</AutocompleteSelect></div></section>
    <section><div className="section-title"><b><Layers size={16}/> 图层</b><button title="添加图层" onClick={()=>file.current?.click()}><ImagePlus size={17}/></button></div><p className="hint">勾选参与生成的图层；眼睛控制画布显示。</p><div className="layer-list">{[...p.layers].reverse().map(l=><div key={l.id} className={'layer '+(p.active===l.id?'active':'')} onClick={()=>setP({...p,active:l.id})}><button title={l.visible?'隐藏':'显示'} onClick={e=>{e.stopPropagation();patch({layers:p.layers.map(x=>x.id===l.id?{...x,visible:!x.visible}:x)});}}>{l.visible?<Eye size={15}/>:<EyeOff size={15}/>}</button><img className="checker" src={l.source}/><span>{l.name}</span>{l.locked&&<Lock size={12}/>}<input type="checkbox" title="参与生成" aria-label={`${l.name} 参与生成`} checked={l.reference} onChange={e=>patch({layers:p.layers.map(x=>x.id===l.id?{...x,reference:e.target.checked}:x)})}/></div>)}</div><div className="layer-actions"><button title="上移" disabled={!layer} onClick={()=>reorder(1)}><ArrowUp size={16}/></button><button title="下移" disabled={!layer} onClick={()=>reorder(-1)}><ArrowDown size={16}/></button><button title="复制图层" disabled={!layer} onClick={()=>{if(layer&&p.layers.length<50){const copy={...layer,id:crypto.randomUUID(),name:layer.name+' 副本'};patch({layers:[...p.layers,copy],active:copy.id});}}}><Copy size={15}/></button><button title="锁定移动" disabled={!layer} onClick={()=>editLayer({locked:!layer?.locked})}>{layer?.locked?<Lock size={15}/>:<Unlock size={15}/>}</button><button title="删除图层" disabled={!layer||layer.locked} onClick={()=>patch({layers:p.layers.filter(l=>l.id!==p.active),active:null})}><Trash2 size={15}/></button></div>{layer&&<div className="layer-props"><input aria-label="图层名称" value={layer.name} onChange={e=>editLayer({name:e.target.value})}/><div className="fields"><label>X<input type="number" disabled={layer.locked} value={layer.x} onChange={e=>editLayer({x:+e.target.value})}/></label><label>Y<input type="number" disabled={layer.locked} value={layer.y} onChange={e=>editLayer({y:+e.target.value})}/></label><label>缩放 %<input type="number" min="1" max="2000" disabled={layer.locked} value={Math.round(layer.scale*100)} onChange={e=>editLayer({scale:Math.max(.01,Math.min(20,+e.target.value/100))})}/></label></div><label>不透明度 {Math.round(layer.opacity*100)}%<input type="range" min="0" max="100" value={layer.opacity*100} onChange={e=>editLayer({opacity:+e.target.value/100})}/></label></div>}</section>
    <section className="generation"><label>操作<AutocompleteSelect value={p.mode} onChange={e=>{const mode=e.target.value as Mode;patch({mode,...(mode==='panorama'?{width:2048,height:1024,mask:null}:{})});if(mode==='brush'||mode==='circle')setTool(mode);}}>{Object.entries(modes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</AutocompleteSelect></label><label>提示词<textarea rows={5} placeholder="描述要生成的画面，或如何修改选中的参考图层…" value={p.prompt} onChange={e=>setP({...p,prompt:e.target.value})}/></label><p className="hint">{p.layers.filter(l=>l.visible&&l.reference).length} 个可见图层参与生成 · 图层按从底到顶对应参考图 1、2…</p><details><summary>生成参数 <ChevronDown size={14}/></summary><label>负面提示词<input value={p.negative} onChange={e=>setP({...p,negative:e.target.value})}/></label><div className="fields"><label>步数<input type="number" min="1" max="80" value={p.steps} onChange={e=>setP({...p,steps:+e.target.value})}/></label><label>引导强度<input type="number" min="1" max="10" step="0.5" value={p.cfg} onChange={e=>setP({...p,cfg:+e.target.value})}/></label></div><label>种子（-1 随机）<input type="number" value={p.seed} onChange={e=>setP({...p,seed:+e.target.value})}/></label></details><Button variant="primary" disabled={busy||!connected||!p.prompt.trim()} onClick={()=>void generate()}>{busy?<Loader2 size={18} className="spin"/>:<Sparkles size={18}/>}生成</Button></section>
   </aside>
  </div>
  {settings&&<Dialog title="模型与服务" onClose={()=>setSettings(false)} info={<InfoTip text="接口地址：127.0.0.1:19877 · 模型按需加载，任务结束释放显存。"/>}><ImageSettings config={config} onSaved={setConfig} token={token} setToken={setToken} notify={notify} onConnect={()=>{sessionStorage.setItem('image-token',token);void connect().then(()=>api('/v1/config')).then(setConfig).catch(notify);}}/></Dialog>}
  {message&&<Toast close={()=>setMessage('')}>{message}</Toast>}
  <input hidden ref={file} type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{if(e.target.files)void addFiles(e.target.files);e.target.value='';}}/>
  <input hidden ref={projectFile} type="file" accept=".laimage,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void importProject(f);e.target.value='';}}/>
  <input hidden ref={maskFile} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void(async()=>{if(f.size>32*1024*1024)throw Error('遮罩不能超过 32 MB');const source=await dataURL(f),im=await loadImage(source);if(im.width!==p.width||im.height!==p.height)throw Error('遮罩尺寸必须与画布一致');patch({mask:source,mode:'mask'});setTool('brush');})().catch(notify);e.target.value='';}}/>
 </div>;
}
initializeTheme('image');
initializeUIPreferences('image');
if(isTauri()&&getUIPreferences().maximizeOnStart)void getCurrentWindow().maximize().catch(error=>console.error('无法在启动时最大化窗口',error));
createRoot(document.getElementById('root')!).render(<App/>);
