import {Plus,Trash2,Star} from 'lucide-react';
import {EditableTitle} from '../../../packages/ui/src/EditableTitle';
import {confirmAction} from '../../../packages/ui/src/confirm';
import {uid,type CharacterSkill} from './types';

export function CharacterSkills({value,onChange}:{value:CharacterSkill[];onChange:(skills:CharacterSkill[])=>void}){
 const update=(id:string,patch:Partial<CharacterSkill>)=>onChange(value.map(skill=>skill.id===id?{...skill,...patch}:skill));
 const ordered=[...value].sort((a,b)=>b.rating-a.rating);
 return <section className="character-skills" aria-label="角色技能管理"><div className="character-skills-heading"><h3>技能管理</h3><button type="button" onClick={()=>onChange([...value,{id:uid(),name:'新技能',description:'',video_prompt:'',rating:0}])}><Plus size="1rem"/>添加技能</button></div><p className="hint">按星级从高到低排列。动画提示词可供生成视频时引用。</p>{!value.length&&<p className="hint">尚未添加技能。</p>}{ordered.map(skill=><section className="character-skill" key={skill.id}><div className="character-skill-heading"><EditableTitle title={skill.name} label="技能名称" save={name=>update(skill.id,{name})}/><button type="button" aria-label={'删除技能：'+skill.name} onClick={async()=>{if(await confirmAction('删除技能“'+skill.name+'”？历史版本会保留。'))onChange(value.filter(item=>item.id!==skill.id));}}><Trash2 size="1rem"/></button></div><div className="asset-rating-field"><span>星级（排序）</span><div className="asset-rating-controls" role="group" aria-label={skill.name+'星级'}>{[1,2,3,4,5].map(star=><button type="button" key={star} className={star<=skill.rating?'rated':''} aria-label={star+'星'} aria-pressed={star===skill.rating} onClick={()=>update(skill.id,{rating:star})}><Star size="1.125rem" fill={star<=skill.rating?'currentColor':'none'}/></button>)}<button type="button" className="asset-rating-clear" disabled={!skill.rating} onClick={()=>update(skill.id,{rating:0})}>清空</button></div></div><label>技能描述<textarea value={skill.description} onChange={event=>update(skill.id,{description:event.target.value})} placeholder="技能效果、使用条件与限制…"/></label><label>视频提示词（动画描述）<textarea value={skill.video_prompt} onChange={event=>update(skill.id,{video_prompt:event.target.value})} placeholder="起手姿势、动作过程、特效变化、收势与镜头运动…"/></label></section>)}</section>;
}
