import {forwardRef,useEffect,useImperativeHandle,useRef} from 'react';
import {Schema,Fragment,Slice,Node as PMNode} from '@milkdown/kit/prose/model';
import {EditorState,TextSelection} from '@milkdown/kit/prose/state';
import {EditorView} from '@milkdown/kit/prose/view';
import {keymap} from '@milkdown/kit/prose/keymap';
import {baseKeymap} from '@milkdown/kit/prose/commands';
import {history,undo,redo,closeHistory} from '@milkdown/kit/prose/history';
import type {Asset} from './types';
import {mentionParts} from './mentionText';
export const mentionSchema=new Schema({nodes:{doc:{content:'paragraph'},paragraph:{content:'inline*',whitespace:'pre',parseDOM:[{tag:'p'}],toDOM:()=>['p',0]},text:{group:'inline'},hard_break:{inline:true,group:'inline',selectable:false,parseDOM:[{tag:'br'}],toDOM:()=>['br'],leafText:()=> '\n'},mention:{inline:true,group:'inline',atom:true,attrs:{id:{},name:{},source:{}},parseDOM:[{tag:'span[data-asset-id]',getAttrs:element=>{const el=element as HTMLElement;const id=el.dataset.assetId;const name=el.dataset.assetName;const source=el.dataset.assetSource;return id&&name!==undefined&&source!==undefined?{id,name,source}:false;}}],toDOM:n=>['span',{'data-asset-id':n.attrs.id,'data-asset-name':n.attrs.name,'data-asset-source':n.attrs.source,contenteditable:'false'},'@'+n.attrs.name],leafText:n=>n.attrs.source}}});
export function inlineNodes(text:string,assets:Asset[]){const nodes:PMNode[]=[];for(const p of mentionParts(text.replace(/\r\n?/g,'\n'),assets)){if(p.asset)nodes.push(mentionSchema.nodes.mention.create({id:p.asset.id,name:p.asset.name,source:p.text}));else p.text.split('\n').forEach((line,i)=>{if(i)nodes.push(mentionSchema.nodes.hard_break.create());if(line)nodes.push(mentionSchema.text(line));});}return nodes;}
export function documentText(doc:PMNode){return doc.textBetween(0,doc.content.size,'\n',n=>n.type.name==='mention'?n.attrs.source:'\n');}
function positionAt(doc:PMNode,offset:number){let result=1,used=0;for(let i=0;i<doc.firstChild!.childCount;i++){const node=doc.firstChild!.child(i);const len=node.isText?node.text!.length:node.type.name==='mention'?node.attrs.source.length:1;if(used+len>=offset)return result+(node.isText?Math.max(0,offset-used):offset>used?node.nodeSize:0);used+=len;result+=node.nodeSize;}return result;}
export function clipboardPlainText(data:DataTransfer){if(data.types.includes('text/plain'))return data.getData('text/plain');const html=data.getData('text/html');if(!html)return '';const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,style,template,noscript').forEach(n=>n.remove());doc.querySelectorAll('br').forEach(n=>n.replaceWith('\n'));doc.querySelectorAll('p,div,li,tr,h1,h2,h3,blockquote').forEach(n=>n.append('\n'));return (doc.body.textContent||'').replace(/\n+$/,'');}
export type MentionEditorHandle={focus:()=>void;contains:(node:Node)=>boolean;getBoundingClientRect:()=>DOMRect|undefined;insert:(start:number,end:number,text:string)=>void};
type Props={value:string;assets:Asset[];onInput:(text:string,cursor:number)=>void;onCaret:(cursor:number)=>void;onEscape:()=>void;onHover?:(asset:Asset|null,rect?:DOMRect)=>void};
export const MentionEditor=forwardRef<MentionEditorHandle,Props>(function MentionEditor(props,ref){
 const host=useRef<HTMLDivElement>(null),view=useRef<EditorView|undefined>(undefined),latest=useRef(props),emitted=useRef(props.value);latest.current=props;
 useImperativeHandle(ref,()=>({focus:()=>view.current?.focus(),contains:n=>!!host.current?.contains(n),getBoundingClientRect:()=>host.current?.getBoundingClientRect(),insert:(start,end,text)=>{const v=view.current;if(!v)return;const from=positionAt(v.state.doc,start),to=positionAt(v.state.doc,end);const content=Fragment.fromArray(inlineNodes(text,latest.current.assets));const tr=v.state.tr.replaceWith(from,to,content);tr.setSelection(TextSelection.create(tr.doc,from+content.size));v.dispatch(closeHistory(tr).scrollIntoView());v.focus();}}),[]);
 useEffect(()=>{const doc=mentionSchema.node('doc',null,[mentionSchema.node('paragraph',null,inlineNodes(latest.current.value,latest.current.assets))]);
 const v=new EditorView(host.current!,{state:EditorState.create({schema:mentionSchema,doc,plugins:[history(),keymap({'Mod-z':undo,'Mod-y':redo,'Mod-Shift-z':redo,Enter:(state,dispatch)=>{dispatch?.(state.tr.replaceSelectionWith(mentionSchema.nodes.hard_break.create()).scrollIntoView());return true;},'Shift-Enter':(state,dispatch)=>{dispatch?.(state.tr.replaceSelectionWith(mentionSchema.nodes.hard_break.create()).scrollIntoView());return true;}}),keymap(baseKeymap)]}),attributes:state=>({'data-empty':String(state.doc.firstChild?.content.size===0),class:'mention-input',role:'textbox','aria-label':'画面与动作','aria-multiline':'true','data-placeholder':'描述画面与动作，输入 @ 引用角色、场景或道具…'}),
 dispatchTransaction(tr){v.updateState(v.state.apply(tr));const cursor=v.state.doc.textBetween(0,v.state.selection.from,'\n',n=>n.type.name==='mention'?n.attrs.source:'\n').length;if(tr.docChanged){const text=documentText(v.state.doc);if(text!==emitted.current){emitted.current=text;latest.current.onInput(text,cursor);}else latest.current.onCaret(cursor);}else latest.current.onCaret(cursor);},
 handleKeyDown:(_,e)=>{if(e.key==='Escape'){latest.current.onEscape();return true;}return false;},
 handlePaste:(v,e)=>{if(!e.clipboardData)return false;e.preventDefault();v.dispatch(v.state.tr.replaceSelection(new Slice(Fragment.fromArray(inlineNodes(clipboardPlainText(e.clipboardData),latest.current.assets)),0,0)).scrollIntoView());return true;},
 handleDrop:()=>true,
 clipboardTextSerializer:slice=>slice.content.textBetween(0,slice.content.size,'\n',n=>n.type.name==='mention'?'@'+n.attrs.name:'\n'),
 nodeViews:{mention(node,editor,getPos){const dom=document.createElement('span');dom.className='inline-asset';dom.dataset.assetId=node.attrs.id;dom.dataset.assetName=node.attrs.name;dom.dataset.assetSource=node.attrs.source;dom.contentEditable='false';const label=document.createElement('span');label.className='inline-asset-label';dom.addEventListener('mouseenter',()=>{const asset=latest.current.assets.find(a=>a.id===node.attrs.id);latest.current.onHover?.(asset||null,dom.getBoundingClientRect());});dom.addEventListener('mouseleave',()=>latest.current.onHover?.(null));label.textContent='@'+node.attrs.name;dom.append(label);const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.className='inline-asset-remove';remove.setAttribute('aria-label','删除引用 '+node.attrs.name);remove.addEventListener('mousedown',e=>e.preventDefault());remove.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const pos=getPos();if(pos!==undefined)editor.dispatch(closeHistory(editor.state.tr.delete(pos,pos+node.nodeSize)));latest.current.onHover?.(null);editor.focus();});dom.append(remove);return{dom,ignoreMutation:mutation=>mutation.type!=='selection',stopEvent:e=>e.target===remove};}},
 });view.current=v;return()=>{v.destroy();view.current=undefined;};},[]);
 useEffect(()=>{const v=view.current;if(!v||props.value===emitted.current)return;const tr=v.state.tr.replaceWith(0,v.state.doc.content.size,mentionSchema.node('paragraph',null,inlineNodes(props.value,props.assets))).setMeta('addToHistory',false);v.updateState(v.state.apply(tr));emitted.current=props.value;},[props.value,props.assets]);
 return <div ref={host} className="mention-editor-host"/>;
});
