import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,Clapperboard,Boxes,ArrowLeft,Plus,Smartphone,RefreshCw,Download} from 'lucide-react';
import {Autocomplete,initializeTheme} from '@local-ai/ui';
import {api,request,setMobileToken,download} from './api';
import {useProject} from './useProject';
import {type Project,type Shot,type Asset,newEpisode,newShot,newAsset,uid} from './types';
import {ShotDuration} from './ShotDuration';
import {ShotPresetField} from './ShotPresetField';
import {mentionIds} from './mentionText';
import '../../../packages/ui/src/styles.css';
import './mobile.css';

initializeTheme('story');
setMobileToken(localStorage.getItem('story-mobile-token')||'');
const scannedCode=new URLSearchParams(location.hash.slice(1)).get('pair')||'';
if(scannedCode)history.replaceState(null,'',location.pathname);
async function pairRequest(path:string,data:unknown){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await res.json();if(!res.ok)throw Error(body.detail||'连接失败');return body;}
function storedPair(){try{return JSON.parse(sessionStorage.getItem('story-pending-pair')||'null') as {id:string;secret:string}|null;}catch{return null;}}
function Media({pid,path,audio=false}:{pid:string;path:string;audio?:boolean}){
 const [url,setUrl]=useState('');
 useEffect(()=>{let alive=true,object='';setUrl('');if(path)request('/v1/projects/'+pid+'/'+path).then(r=>r.blob()).then(blob=>{if(alive){object=URL.createObjectURL(blob);setUrl(object);}}).catch(()=>{});return()=>{alive=false;if(object)URL.revokeObjectURL(object);};},[pid,path]);
 return url?(audio?<audio controls preload="metadata" src={url}/>:<a href={url} target="_blank" rel="noreferrer"><img src={url} alt="素材预览" loading="lazy"/></a>):<div className="mobile-media-empty">{path?'图片读取中…':'暂无图片'}</div>;
}
export function MobileApp(){
 const [ready,setReady]=useState(false),[checking,setChecking]=useState(true),[code,setCode]=useState(scannedCode),[pair,setPair]=useState(storedPair),[deviceName,setDeviceName]=useState('我的手机'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [projects,setProjects]=useState<{id:string;name:string;episodes:number}[]>([]),[cid,setCid]=useState(''),[eid,setEid]=useState(''),[tab,setTab]=useState<'script'|'shots'|'assets'|'history'>('script');
 const [versions,setVersions]=useState<{id:string;revision:number;reason:string;updated:string}[]>([]),[snapshot,setSnapshot]=useState<Project>();
 const {project:p,edit,load,flush,status,current}=useProject(e=>setError(String(e)));
 const episode=p?.chapters.flatMap(c=>c.episodes).find(e=>e.id===eid);
 const refresh=async()=>setProjects(await api('/v1/projects'));
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{if(code||pair){setChecking(false);return;}api('/v1/session').then(()=>{setReady(true);return refresh();}).catch(()=>setReady(false)).finally(()=>setChecking(false));},[]);
 useEffect(()=>{if(!pair)return;let stopped=false;const poll=async()=>{try{const result=await pairRequest('/pair/'+pair.id+'/poll',{secret:pair.secret});if(stopped)return;if(result.status==='approved'){setMobileToken(result.token);sessionStorage.removeItem('story-pending-pair');setPair(null);setCode('');setReady(true);setError('');await refresh();}else if(result.status==='rejected'){sessionStorage.removeItem('story-pending-pair');setPair(null);setError('电脑已拒绝绑定，请重新扫码。');}}catch(e){if(!stopped){setError(String(e));sessionStorage.removeItem('story-pending-pair');setPair(null);}}};void poll();const timer=setInterval(poll,2000);return()=>{stopped=true;clearInterval(timer);};},[pair]);
 useEffect(()=>{if(tab!=='history'||!p)return;api<typeof versions>('/v1/projects/'+p.id+'/history').then(setVersions).catch(e=>setError(String(e)));},[tab,p?.id,p?.revision]);
 useEffect(()=>{const retry=()=>{if(ready)void act(async()=>{await flush();await refresh();});};window.addEventListener('online',retry);return()=>window.removeEventListener('online',retry);},[ready]);
 async function openProject(id:string){await flush();const next=await api<Project>('/v1/projects/'+id);const draft=localStorage.getItem('story-draft-'+id);load(next);setCid(next.chapters[0]?.id||'');setEid(next.chapters.flatMap(c=>c.episodes)[0]?.id||'');setSnapshot(undefined);if(draft&&window.confirm('发现未保存的手机草稿，是否恢复？')){try{const savedDraft=JSON.parse(draft) as Project;if(savedDraft.id===id)edit(value=>Object.assign(value,savedDraft));}catch{setError('草稿无法读取');}}}
 function updateEpisode(fn:(e:NonNullable<typeof episode>)=>void){edit(project=>{const target=project.chapters.flatMap(c=>c.episodes).find(e=>e.id===eid);if(target)fn(target);});}
 function updateShot(id:string,patch:Partial<Shot>){updateEpisode(e=>{const shot=e.shots.find(s=>s.id===id);if(shot)Object.assign(shot,patch);});}
 function updateAsset(id:string,patch:Partial<Asset>){edit(project=>{const asset=project.assets.find(a=>a.id===id);if(asset)Object.assign(asset,patch);});}
 const draftDownload=()=>p&&download(new Blob([JSON.stringify(current.current,null,2)],{type:'application/json'}),p.name+'-手机草稿.json');
 if(checking)return <main className="mobile-auth"><Smartphone/><h1>正在连接电脑…</h1></main>;
 if(!ready||code||pair)return <main className="mobile-auth"><Smartphone size="2.5rem"/><span className="mobile-kicker">STORY · 手机创作</span><h1>{pair?'等待电脑确认':'绑定你的创作电脑'}</h1><p>手机和电脑连接同一局域网，电脑保持运行。</p>{pair?<p role="status">请在电脑「设置 → 手机访问」中允许此设备。</p>:code?<><label>设备名称<input maxLength={80} value={deviceName} onChange={e=>setDeviceName(e.target.value)}/></label><button className="mobile-primary" disabled={busy||!deviceName.trim()} onClick={()=>act(async()=>{const result=await pairRequest('/pair/claim',{code,name:deviceName});sessionStorage.setItem('story-pending-pair',JSON.stringify(result));setPair(result);setCode('');})}>请求绑定</button></>:<p>请在电脑「设置 → 手机访问」开启访问，生成二维码并用手机相机扫描。</p>}{error&&<p role="alert" className="mobile-error">{error}</p>}</main>;
 return <div className="mobile-app"><header className="mobile-header">{p?<button aria-label="返回剧集" disabled={busy} onClick={()=>act(async()=>{await flush();load(null);await refresh();})}><ArrowLeft/></button>:<BookOpen/>}<div><strong>{p?.name||'我的剧集'}</strong><small>{p?status:'STORY · 手机创作'}</small></div><button aria-label="刷新" disabled={busy} onClick={()=>act(async()=>{await flush();if(p)await openProject(p.id);else await refresh();})}><RefreshCw size="1.125rem"/></button></header>
 {error&&<aside className="mobile-alert" role="alert"><p>{error}</p>{p&&<div className="mobile-actions"><button onClick={()=>void draftDownload()}><Download size="1rem"/>下载当前草稿</button><button onClick={()=>act(()=>flush())}>重试保存</button><button onClick={()=>{if(window.confirm('丢弃手机未保存修改并载入电脑最新版本？建议先下载草稿。'))void act(async()=>{const next=await api<Project>('/v1/projects/'+p.id);load(next);localStorage.removeItem('story-draft-'+p.id);});}}>载入最新版本</button></div>}<button onClick={()=>setError('')}>收起提示</button></aside>}
 {!p?<main className="mobile-library"><h1>随时接着写</h1><p>选择一部剧，继续编辑剧本与分镜。</p>{projects.map(project=><button className="mobile-project" key={project.id} disabled={busy} onClick={()=>act(()=>openProject(project.id))}><BookOpen/><span><b>{project.name}</b><small>{project.episodes} 话</small></span></button>)}{!projects.length&&<p>还没有剧集，请先在电脑创建项目。</p>}<button className="mobile-logout" onClick={()=>{setMobileToken('');setReady(false);}}>退出此手机</button></main>:<><nav className="mobile-tabs" aria-label="内容分类">{([['script','剧本',BookOpen],['shots','分镜',Clapperboard],['assets','资产',Boxes],['history','历史',RefreshCw]] as const).map(([id,label,Icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setSnapshot(undefined);}}><Icon size="1rem"/>{label}</button>)}</nav><main className="mobile-content">
 {(tab==='script'||tab==='shots')&&<section className="mobile-episode-nav"><Autocomplete label="章节" allowCustom={false} value={cid} onChange={id=>{setCid(id);setEid(p.chapters.find(c=>c.id===id)?.episodes[0]?.id||'');}} options={p.chapters.map(c=>({value:c.id,label:c.title}))}/><Autocomplete label="话" allowCustom={false} value={eid} onChange={setEid} options={(p.chapters.find(c=>c.id===cid)?.episodes||[]).map(e=>({value:e.id,label:e.title}))}/><div className="mobile-actions"><button onClick={()=>{const name=window.prompt('新章 / 季名称');if(name?.trim()){const id=uid();edit(project=>project.chapters.push({id,title:name.trim(),episodes:[]}));setCid(id);setEid('');}}}>新增章节</button><button onClick={()=>{const chapter=p.chapters.find(c=>c.id===cid)||p.chapters.at(-1);if(!chapter){setError('请先新增章节');return;}const title=window.prompt('新增到「'+chapter.title+'」的话名称');if(title?.trim()){const next=newEpisode(title.trim());edit(project=>project.chapters.find(c=>c.id===chapter.id)!.episodes.push(next));setEid(next.id);}}}>新增一话</button></div></section>}
 {tab==='script'&&(episode?<section className="mobile-card"><label>话标题<input value={episode.title} onChange={e=>updateEpisode(ep=>{ep.title=e.target.value;})}/></label><label>文字剧本 · Markdown<textarea className="mobile-script" value={episode.script} onChange={e=>updateEpisode(ep=>{ep.script=e.target.value;})} placeholder="开始写故事…"/></label></section>:<p>请新增或选择一话。</p>)}
 {tab==='shots'&&<>{episode&&<button className="mobile-primary" onClick={()=>updateEpisode(e=>e.shots.push(newShot()))}><Plus size="1rem"/>添加镜头</button>}{episode?.shots.map((shot,index)=><section className="mobile-card" key={shot.id}><div className="mobile-shot-heading"><b>镜 {(index+1).toString().padStart(2,'0')}</b><label className="mobile-check"><input type="checkbox" checked={!shot.disabled} onChange={e=>updateShot(shot.id,{disabled:!e.target.checked})}/>启用</label></div><Media pid={p.id} path={shot.image}/><label>标题<input value={shot.title} onChange={e=>updateShot(shot.id,{title:e.target.value})}/></label><label>场景题头<input value={shot.scene} onChange={e=>updateShot(shot.id,{scene:e.target.value})}/></label><div className="mobile-fields"><ShotDuration value={shot.duration} fps={p.fps} onChange={duration=>updateShot(shot.id,{duration})}/>{([['shot_size','景别'],['angle','角度'],['camera_move','运镜'],['lighting','光线']] as const).map(([key,label])=><ShotPresetField key={key} field={key} label={label} value={shot[key]} onChange={value=>updateShot(shot.id,{[key]:value})}/>)}</div><label>画面与动作<textarea value={shot.description} onChange={e=>updateShot(shot.id,{description:e.target.value,asset_ids:[...new Set([...shot.asset_ids.filter(id=>!mentionIds(shot.description,p.assets).includes(id)),...mentionIds(e.target.value,p.assets)])]})}/></label><Autocomplete label="引用素材" allowCustom={false} value="" placeholder="搜索并引用素材" options={p.assets.map(a=>({value:a.id,label:a.name}))} onChange={id=>{const a=p.assets.find(a=>a.id===id);if(a)updateShot(shot.id,{description:shot.description+` @[${a.name}](asset:${a.id})`,asset_ids:[...new Set([...shot.asset_ids,a.id])]});}}/><details><summary>对白与声音</summary>{([['speaker','说话人'],['delivery','声音方式'],['emotion','情绪'],['dialogue','对白'],['sound','音效'],['subtitle','字幕']] as const).map(([key,label])=><label key={key}>{label}<textarea rows={2} value={shot[key]} onChange={e=>updateShot(shot.id,{[key]:e.target.value})}/></label>)}{shot.audio&&<Media pid={p.id} path={shot.audio} audio/>}</details><button className="mobile-danger" onClick={()=>{if(window.confirm('删除此镜头？修改会保留历史。'))updateEpisode(e=>{e.shots=e.shots.filter(s=>s.id!==shot.id);});}}>删除镜头</button></section>)}{episode&&!episode.shots.length&&<p>暂无分镜，可添加镜头开始编辑。</p>}</>}
 {tab==='assets'&&<><button onClick={()=>edit(project=>project.assets.push(newAsset()))}><Plus size="1rem"/>新增资产</button>{p.assets.map(asset=><section className="mobile-card" key={asset.id}><h2>{asset.name}</h2><Media pid={p.id} path={asset.image}/><label>名称<input value={asset.name} onChange={e=>{const name=e.target.value;edit(project=>{project.assets.find(a=>a.id===asset.id)!.name=name;for(const c of project.chapters)for(const ep of c.episodes)for(const s of ep.shots){s.description=s.description.replaceAll(`@[${asset.name}](asset:${asset.id})`,`@[${name}](asset:${asset.id})`);if(s.speaker===asset.name)s.speaker=name;}});}}/></label><Autocomplete label="资产类型" value={asset.kind} allowCustom={false} options={[{value:'character',label:'角色'},{value:'scene',label:'场景'},{value:'prop',label:'道具'},{value:'other',label:'其他'}]} onChange={value=>updateAsset(asset.id,{kind:value as Asset['kind']})}/>{([['description','设定描述'],['constraints','一致性约束'],...(asset.kind==='character'?[['gender','性别'],['body','体型'],['form','形态'],['clothing','服饰'],['voice_description','声音描述']] as const:[])] as readonly (readonly [keyof Asset,string])[]).map(([key,label])=><label key={key}>{label}<textarea rows={2} value={String(asset[key]??'')} onChange={e=>updateAsset(asset.id,{[key]:e.target.value})}/></label>)}{asset.voice&&<Media pid={p.id} path={asset.voice} audio/>}</section>)}</>}
 {tab==='history'&&<><h2>历史版本</h2>{snapshot?<><button onClick={()=>setSnapshot(undefined)}>返回版本列表</button><h3>{snapshot.name} · 版本 {snapshot.revision}</h3>{snapshot.chapters.map(c=><section className="mobile-card" key={c.id}><h3>{c.title}</h3>{c.episodes.map(ep=><details key={ep.id}><summary>{ep.title}</summary><pre>{ep.script}</pre>{ep.shots.map(s=><div key={s.id}><b>{s.title}</b><pre>{s.description}</pre><p>{s.dialogue}</p></div>)}</details>)}</section>)}</>:versions.map(v=><button className="mobile-project" key={v.id} onClick={()=>act(async()=>setSnapshot((await api('/v1/projects/'+p.id+'/history/'+v.id)).project))}><span><b>版本 {v.revision}</b><small>{v.reason}</small></span></button>)}</>}
 </main></>}
 </div>;
}
const container=document.getElementById('root');
if(container)createRoot(container).render(<MobileApp/>);
