import {useEffect,useState} from 'react';
import {Autocomplete} from '@local-ai/ui';
import {api,post} from './api';
type State={enabled:boolean;port:number;addresses:string[];error:string;devices:{id:string;name:string;expires:number}[];pending:{id:string;name:string;expires:number}[]};
export function MobileSettings(){
 const [state,setState]=useState<State>(),[address,setAddress]=useState(''),[port,setPort]=useState(19879),[qr,setQr]=useState<{url:string;svg:string;expires:number}>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const refresh=async()=>{const next=await api<State>('/v1/mobile');setState(next);setAddress(current=>next.addresses.includes(current)?current:next.addresses[0]||'');return next;};
 useEffect(()=>{let mounted=true;const load=async()=>{try{const next=await api<State>('/v1/mobile');if(!mounted)return;setState(next);setAddress(current=>next.addresses.includes(current)?current:next.addresses[0]||'');}catch(e){if(mounted)setError(String(e));}};void refresh().then(next=>{if(mounted)setPort(next.port);}).catch(e=>setError(String(e)));const timer=setInterval(()=>{setNow(Date.now());void load();},2000);return()=>{mounted=false;clearInterval(timer);};},[]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section className="settings-card mobile-settings"><h2>手机访问</h2><p className="hint">手机与电脑连接同一局域网。扫码后在电脑确认绑定，即可查看和编辑全部剧集；电脑需保持运行。</p><div className="fields"><label>端口<input type="number" min={1024} max={65535} disabled={state?.enabled||busy} value={port} onChange={e=>setPort(+e.target.value)}/></label><button disabled={!state||busy} onClick={()=>act(async()=>{await api('/v1/mobile',{method:'PUT',body:JSON.stringify({enabled:!state!.enabled,port})});setQr(undefined);})}>{state?.enabled?'关闭局域网访问':'开启局域网访问'}</button></div>{(error||state?.error)&&<p role="alert" className="warning">{error||state?.error}</p>}{state?.enabled&&<><label>电脑局域网地址<Autocomplete label="电脑局域网地址" value={address} options={state.addresses} allowCustom={false} onChange={value=>{setAddress(value);setQr(undefined);}}/></label>{!state.addresses.length&&<p className="warning">没有检测到局域网地址，请连接 Wi-Fi 或网线后重试。</p>}<button disabled={!address||busy} onClick={()=>act(async()=>setQr(await post('/v1/mobile/pair',{address})))}>生成 / 刷新绑定二维码</button>{qr&&<div className="mobile-pair-code"><img alt="手机绑定二维码" src={'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(qr.svg)}/><p>{now<qr.expires*1000?`请用手机相机扫码，${Math.ceil((qr.expires*1000-now)/1000)} 秒后过期`:'二维码已过期，请刷新'}</p><small>也可在手机浏览器打开：http://{address}:{state.port}/mobile<br/>绑定时请重新扫码。</small></div>}<p className="hint">无法打开时，请确认手机没有使用访客 Wi-Fi，并允许 Python 的 Windows 防火墙专用网络访问。仅限可信局域网使用。</p></>}{!!state?.pending.length&&<div><h3>等待确认</h3>{state.pending.map(device=><div className="mobile-device" key={device.id}><b>{device.name}</b><div className="actions"><button disabled={busy} onClick={()=>act(()=>post('/v1/mobile/pending/'+device.id,{approve:false}))}>拒绝</button><button className="primary" disabled={busy} onClick={()=>act(()=>post('/v1/mobile/pending/'+device.id,{approve:true}))}>允许绑定</button></div></div>)}</div>}<h3>已绑定设备</h3>{!state?.devices.length?<p className="hint">暂无绑定设备</p>:state.devices.map(device=><div className="mobile-device" key={device.id}><span>{device.name}</span><button disabled={busy} onClick={()=>act(()=>post('/v1/mobile/devices/'+device.id+'/revoke',{}))}>解除绑定</button></div>)}</section>;
}
