import {useRef,useState,type ReactNode} from 'react';
import {Check,Loader2,Pencil,X} from 'lucide-react';
import './EditableTitle.css';
export function EditableTitle({title,save,onError,disabled=false,prefix,label='标题',labels={edit:'重命名',save:'保存',cancel:'取消'},maxLength,className=''}:{title:string;save:(value:string)=>void|Promise<void>;onError?:(message:string)=>void;disabled?:boolean;prefix?:ReactNode;label?:string;labels?:{edit:string;save:string;cancel:string};maxLength?:number;className?:string}){
 const [draft,setDraft]=useState<string|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 const report=(message:string)=>{setError(message);onError?.(message);};
 async function submit(){if(disabled||lock.current||!draft?.trim())return;if(draft.trim()===title){setDraft(null);return;}lock.current=true;setSaving(true);report('');try{await save(draft.trim());setDraft(null);}catch(e){report(String(e));}finally{lock.current=false;setSaving(false);}}
 return <span className={'editable-title '+className}>{prefix}{draft===null?<><strong title={title}>{title}</strong><button type="button" className="editable-title-icon" disabled={disabled} title={labels.edit} aria-label={labels.edit+' '+label} onClick={()=>{setDraft(title);report('');}}><Pencil size=".875rem"/></button></>:<form className="editable-title-form" onSubmit={e=>{e.preventDefault();void submit();}}><input autoFocus onFocus={e=>e.target.select()} aria-label={label} value={draft} maxLength={maxLength} disabled={saving} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.nativeEvent.isComposing||e.keyCode===229){if(e.key==='Enter')e.preventDefault();return;}if(e.key==='Escape'&&!saving){e.preventDefault();setDraft(null);report('');}}}/><button type="submit" className="editable-title-icon" disabled={disabled||saving||!draft.trim()} aria-label={labels.save} title={labels.save}>{saving?<Loader2 size=".9375rem"/>:<Check size=".9375rem"/>}</button><button type="button" className="editable-title-icon" disabled={saving} aria-label={labels.cancel} title={labels.cancel} onClick={()=>{setDraft(null);report('');}}><X size=".9375rem"/></button></form>}{error&&!onError&&<small role="alert">{error}</small>}</span>;
}
