import {useLayoutEffect,useRef,useState} from 'react';
import './split-divider.css';

export function SplitDivider({storageKey,label='调整左右栏宽度',minLeftRem=20,minRightRem=16,defaultRightRem=20.25}:{storageKey:string;label?:string;minLeftRem?:number;minRightRem?:number;defaultRightRem?:number}){
 const ref=useRef<HTMLDivElement>(null);const dragging=useRef<number|null>(null);
 const [ratio,setRatio]=useState<number|null>(()=>{try{const raw=localStorage.getItem(storageKey);const n=Number(raw);return raw!==null&&Number.isFinite(n)&&n>0&&n<1?n:null;}catch{return null;}});
 const [percent,setPercent]=useState(30);
 const measure=()=>{const node=ref.current,parent=node?.parentElement;if(!node||!parent)return null;const rem=parseFloat(getComputedStyle(document.documentElement).fontSize)||16;const width=parent.getBoundingClientRect().width-node.getBoundingClientRect().width;return {parent,rem,width};};
 const clamp=(right:number,width:number,rem:number)=>Math.max(Math.min(minRightRem*rem,width/2),Math.min(right,Math.max(width-minLeftRem*rem,width/2)));
 useLayoutEffect(()=>{const node=ref.current,parent=node?.parentElement;if(!parent)return;const update=()=>{const m=measure();if(!m||m.width<=0)return;const right=clamp(ratio===null?defaultRightRem*m.rem:ratio*m.width,m.width,m.rem);parent.style.setProperty('--split-right',(right/m.rem)+'rem');setPercent(Math.round(right/m.width*100));};update();const observer=new ResizeObserver(update);observer.observe(parent);observer.observe(document.documentElement);return()=>observer.disconnect();},[ratio,minLeftRem,minRightRem,defaultRightRem]);
 const save=(right:number)=>{const m=measure();if(!m||m.width<=0)return;const next=clamp(right,m.width,m.rem)/m.width;setRatio(next);try{localStorage.setItem(storageKey,String(next));}catch{}};
 const move=(x:number)=>{const m=measure();if(m)save(m.parent.getBoundingClientRect().right-x-(ref.current?.getBoundingClientRect().width||0)/2);};
 return <div ref={ref} className="ui-split-divider" role="separator" aria-label={label} aria-orientation="vertical" aria-valuenow={percent} aria-valuetext={'右栏宽度 '+percent+'%'} tabIndex={0} onPointerDown={event=>{if(event.button!==0)return;event.preventDefault();dragging.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);}} onPointerMove={event=>{if(dragging.current===event.pointerId)move(event.clientX);}} onPointerUp={event=>{if(dragging.current===event.pointerId){move(event.clientX);dragging.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}}} onPointerCancel={()=>{dragging.current=null;}} onLostPointerCapture={()=>{dragging.current=null;}} onDoubleClick={()=>{setRatio(null);try{localStorage.removeItem(storageKey);}catch{}}} onKeyDown={event=>{if(event.key!=='ArrowLeft'&&event.key!=='ArrowRight')return;event.preventDefault();const m=measure();if(m)save((ratio===null?defaultRightRem*m.rem:ratio*m.width)+(event.key==='ArrowLeft'?1:-1)*m.rem);}}/>;
}
